baseurl = "https://www.checklyhq.com"
languageCode = "en-us"
languageLang = "en"
title = "Build and Run Synthetics That Scale"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true

pygmentsCodeFences = true
pygmentsUseClasses = true

disqusShortname = "checkly"

[permalinks]
  blog = "/blog/:year/:month/:title/"

[params]
    description = "Monitoring as code workflow for developers: programmable, fast, reliable."

[[menu.topnav]]
    name = "Documentation"
    url = "/docs/"
    weight = 10
[[menu.topnav]]
    name = "Guides"
    url = "/guides"
    weight = 20

[[menu.started]]
	name = "Overview"
	url = "/docs/"
	weight = 1

[[menu.platform]]
	name = "Monitoring"
	url = "/docs/monitoring/"
	weight = 10

[[menu.platform]]
	name = "Testing"
	url = "/docs/testing/"
	weight = 20

[[menu.platform]]
    name = "CLI"
    url = "/docs/cli/"
    weight = 30


[[menu.resources]]
	name = "API checks"
	url = "/docs/api-checks/"
	weight = 20

[[menu.resources]]
	name = "Browser checks"
	url = "/docs/browser-checks/"
	weight = 30

[[menu.resources]]
	name = "Groups"
	url = "/docs/groups/"
	weight = 40

[[menu.resources]]
	name = "Alerting"
	url = "/docs/alerting/"
	weight = 50

[[menu.resources]]
	name = "Maintenance windows"
	url = "/docs/maintenance-windows/"
	weight = 70

[[menu.resources]]
    name = "Dashboards"
    url = "/docs/dashboards"
    weight = 80

[[menu.resources]]
	name = "Accounts & Users"
	url = "/docs/accounts-users/"
	weight = 90

[[menu.resources]]
	name = "Private Locations"
	url = "/docs/private-locations/"
	weight = 95

[[menu.resources]]
	name = "Reporting"
	url = "/docs/reporting/"
	weight = 110

[[menu.resources]]
	name = "Analytics"
	url = "/docs/anlytics/"
	weight = 105

[[menu.resources]]
    name = "Runtimes"
    url = "/docs/runtimes/"
    weight = 120

[[menu.resources]]
    name = "Snippets"
    url = "/docs/snippets/"
    weight = 130

[[menu.integrations]]
	name = "Integrations"
	url = "/docs/integrations/"
	weight = 10

[[menu.integrations]]
	name = "CI/CD integration"
	url = "/docs/cicd/"
	weight = 20

[[menu.integrations]]
	name = "Terraform provider"
	url = "/docs/terraform-provider/"
	weight = 30

[[menu.integrations]]
	name = "Pulumi provider"
	url = "/docs/pulumi-provider/"
	weight = 40


[[menu.reference]]
    name = "CLI Commands"
    url = "/docs/cli/command-line-reference"
    weight = 170

[[menu.reference]]
    name = "CLI Constructs"
    url = "/docs/cli/constructs-reference"
    weight = 180

[[menu.reference]]
    name = "Runtime specs"
    url = "/docs/runtimes/specs/"
    weight = 190

[[menu.reference]]
    name = "API Reference"
    url = "https://developers.checklyhq.com"
    weight = 200

[[menu.learn]]
	name = "Getting started"
	pre = "/learn/icons/getting-started.svg"
	weight = 10

[[menu.learn]]
	name = "E2E examples"
	pre = "/learn/icons/e2e.svg"
	weight = 20

[[menu.learn]]
	name = "Pages & frames"
	pre = "/learn/icons/pages.svg"
	weight = 30

[[menu.learn]]
	name = "Network & state"
	pre = "/learn/icons/network.svg"
	weight = 32

[[menu.learn]]
	name = "Best practices"
	pre = "/learn/icons/best-practices.svg"
	weight = 60

[[menu.learn]]
	name = "Performance"
	pre = "/learn/icons/performance.svg"
	weight = 50

[[menu.learn]]
	name = "Scraping"
	pre = "/learn/icons/scraping.svg"
	weight = 45

[[menu.learn]]
	name = "Debugging"
	pre = "/learn/icons/errors.svg"
	weight = 60

[[menu.learn]]
	name = "Miscellaneous"
	pre = "/learn/icons/misc.svg"
	weight = 1000

[markup.goldmark.renderer]
unsafe = true
