baseurl = "https://www.checklyhq.com"
languageCode = "en-us"
languageLang = "en"
title = "Delightful Active Monitoring for Developers"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableGitInfo = false
enableRobotsTXT = true

pygmentsCodeFences = true
pygmentsUseClasses = true

disqusShortname = "checkly"

[permalinks]
  blog = "/blog/:year/:month/:title/"

[params]
    description = "Checkly is the API & E2E monitoring platform for the modern stack: programmable, flexible and loving JavaScript."

[[menu.docs]]
	name = "Monitoring"
	url = "/docs/monitoring/"
	pre="/docs/images/icons/monitoring.svg"
	weight = 10


[[menu.docs]]
	name = "API checks"
	url = "/docs/api-checks/"
	pre="/docs/images/icons/api.svg"
	weight = 20

[[menu.docs]]
	name = "Browser checks"
	url = "/docs/browser-checks/"
	pre="/docs/images/icons/browser-checks.svg"
	weight = 30

[[menu.docs]]
	name = "Groups"
	url = "/docs/groups/"
	pre="/docs/images/icons/groups.svg"
	weight = 40

[[menu.docs]]
	name = "Alerting"
	url = "/docs/alerting/"
	pre="/docs/images/icons/alerting.svg"
	weight = 50

[[menu.docs]]
	name = "CI/CD integration"
	url = "/docs/cicd/"
	pre="/docs/images/icons/ci-cd.svg"
	weight = 60

[[menu.docs]]
	name = "Maintenance windows"
	url = "/docs/maintenance-windows/"
	pre="/docs/images/icons/maintenance-windows.svg"
	weight = 70

[[menu.docs]]
	name = "Dashboards"
	url = "/docs/dashboards/"
	pre="/docs/images/icons/dashboards.svg"
	weight = 80

[[menu.docs]]
	name = "Teams"
	url = "/docs/teams/"
	pre="/docs/images/icons/teams.svg"
	weight = 90

[[menu.docs]]
	name = "Integrations"
	url = "/docs/integrations/"
	pre="/docs/images/icons/integrations.svg"
	weight = 100

[[menu.docs]]
	name = "Reporting"
	url = "/docs/reporting/"
	pre="/docs/images/icons/reporting.svg"
	weight = 110

[[menu.docs]]
	name = "Headless Recorder"
	url = "/docs/headless-recorder/"
	pre="/docs/images/icons/headless-recorder.svg"
	weight = 9999

[[menu.learn]]
	name = "Getting Started"
	pre = "/learn/icons/getting-started.svg"
	weight = 10

[[menu.learn]]
	name = "E2E"
	pre = "/learn/icons/e2e.svg"
	weight = 20

[[menu.learn]]
	name = "Session Management"
	pre = "/learn/icons/session-management.svg"
	weight = 30

[[menu.learn]]
	name = "Best Practices"
	pre = "/learn/icons/best-practices.svg"
	weight = 60

[[menu.learn]]
	name = "Performance"
	pre = "/learn/icons/performance.svg"
	weight = 40

[[menu.learn]]
	name = "Scraping"
	pre = "/learn/icons/scraping.svg"
	weight = 50

[[menu.learn]]
	name = "Miscellaneous"
	pre = "/learn/icons/misc.svg"
	weight = 1000

[markup.goldmark.renderer]
unsafe = true
